defaults:
  - _self_

subst_params:
  path_to_configs: ${hydra:runtime.cwd}/multilang_wsi_evaluation/conf/model_vec/subst_params
  mask_count: [4]
  lang_substs:
    en:
      - en_and_left
      - en_and_right
    ru:
      - ru_and_left
      - ru_and_right
    sl:
      - sl_and_left
      - sl_and_right
    bg:
      - bg_and_left
      - bg_and_right
    ja:
      - ja_and_left
      - ja_and_right
    it:
      - it_and_left
      - it_and_right
    zh:
      - zh_and_left
      - zh_and_right

_target_: SubstWSI_rombek.src.VectorizingPipeline.VectorizingPipeline

substs_overrides:
  path_to_substs: ${hydra:runtime.cwd}/SubstWSI_rombek/substs
  model_path: ${hydra:runtime.cwd}/xlmr_large_cwm_multi/model.pt
#  fill_masks: 4
  topk: 150
  debug: False
  version: 4
  beam_search: True

preprocessor_config:
  disable: False

lemma_config:
  mode: word
  lemmatizer_name: stanza
#  cache_path: ${hydra:runtime.cwd}/SubstWSI_rombek/.lemma_cachecwm_multi_and
  cache_path: ${hydra:runtime.cwd}/SubstWSI_rombek/12345121476
  lemmas_similarity_threshold: 1.0

vec_config:
  patterns_probs: 0
  vec_mode: rombek
  base_vec: tfidf # count
  comb_mode: mean
  ood_mode: eps
  top_k: 150
  ood_prob: 1e-7
#  min_df: 0.05
#  max_df: 0.95
