defaults:
  - _self_
  - subst_params:
    - es_y_1
    - es_y_2
    - es_por_ejemplo_1
    - es_por_ejemplo_2
    - es_incluso_1
    - es_incluso_2
    - mask

_target_: substwsi_artem.SubstVectorizerA
path_to_substs: ../../substWSI_Artem/lscd_es

subst_params:
  es_y_1:
    weight: 0.25
  es_y_2:
    weight: 0.25
  es_por_ejemplo_1:
    weight: 0.0625
  es_por_ejemplo_2:
    weight: 0.0625
  es_incluso_1:
    weight: 0.0625
  es_incluso_2:
    weight: 0.0625
  mask:
    weight: 0.25

#vectorizers
subst_vect:
  _target_: sklearn.feature_extraction.text.TfidfVectorizer
  token_pattern: (?u)\b\w+\b
  min_df: 0.03
  max_df: 0.9
  analyzer: word
  ngram_range:
    _target_: builtins.tuple
    _args_:
      - [ 1, 1 ]

subst_vect_weak:
  _target_: sklearn.feature_extraction.text.TfidfVectorizer
  token_pattern: (?u)\b\w+\b
  analyzer: word
  ngram_range:
    _target_: builtins.tuple
    _args_:
      - [ 1, 1 ]


# substs processing
subst_pipeline:
  _target_: substwsi_artem.SubstPipeline
  StripAndLower:
    _target_: substwsi_artem.src.pipeline.component.StripAndLower
    order: 1
  MultiSubstProcess:
    _target_: substwsi_artem.src.pipeline.component.MultiSubstProcess
    multi_select: last
    order: 2
  Stemmer:
    _target_: substwsi_artem.src.pipeline.component.Stemmer
    language: spanish
    order: 3
  WeightedCombination:
    _target_: substwsi_artem.src.pipeline.component.WeightedCombination
    missing_prob: min
    order: 4
  # MeanCombination:
  #   _target_: substwsi_artem.src.pipeline.component.MeanCombination
  #   comb_mode: prod
  #   missing_prob: min
  #   order: 4
  Filter:
    _target_: substwsi_artem.src.pipeline.component.Filter
    filter_mode: topk
    value: 150
    order: 5